In [91]:
# package import
import pandas as pd
import numpy as np #-- case when

In [92]:
# load the table 
orders = pd.read_csv('/data/input/orders.csv')
returns = pd.read_csv('/data/input/returns.csv')

In [93]:
type(orders.order_id)

pandas.core.series.Series

### .loc[ WHERE, SELECT]

In [95]:
# SELECT order_id, order_date, sales, profit FROM Orders;
orders.loc[  :, 
           ['order_id', 'order_date', 'profit','sales'] 
          ].head(5)

         order_id  order_date  profit  sales
0  CA-2020-152156  08-11-2020    41.9  262.0
1  CA-2020-152156  08-11-2020   219.6  731.9
2  CA-2020-138688  12-06-2020     6.9   14.6
3  US-2019-108966  11-10-2019  -383.0  957.6
4  US-2019-108966  11-10-2019     2.5   22.4

In [96]:
# SELECT * FROM Orders;
orders.loc[ : ].head(5)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

## LIMIT

In [97]:
#SELECT * FROM Orders LIMIT 5;
orders.head(5)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [98]:
#select botton 5 record
orders.tail(5)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [99]:
# select columns

# multi-column [[]]
orders.loc[ :,
           ['order_id', 'order_date', 'profit' ]

].head(1)

#single column []
#orders.loc[ : ,  'order_id']

         order_id  order_date  profit
0  CA-2020-152156  08-11-2020    41.9

## Metadata

In [100]:
#describe - dtypes | info | describe
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     50 non-null     object
 1   order_date   50 non-null     object
 2   ship_date    50 non-null     object
 3   ship_mode    50 non-null     object
 4   customer_id  50 non-null     object
 5   region       50 non-null     object
 6   product_id   50 non-null     object
 7   category     50 non-null     object
 8   sales        50 non-null     float64
 9   quantity     50 non-null     int64
 10  profit       50 non-null     float64
dtypes: float64(2), int64(1), object(8)
memory usage: 4.4+ KB

In [130]:
orders['order_date'] = pd.to_datetime( orders.order_date, errors= 'coerce' )
orders['ship_date'] = pd.to_datetime(  orders.ship_date, errors = 'coerce')
orders['sales'] = orders.sales.astype(float)

In [131]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     50 non-null     object
 1   order_date   50 non-null     datetime64[ns]
 2   ship_date    50 non-null     datetime64[ns]
 3   ship_mode    50 non-null     object
 4   customer_id  50 non-null     object
 5   region       50 non-null     object
 6   product_id   50 non-null     object
 7   category     50 non-null     object
 8   sales        50 non-null     float64
 9   quantity     50 non-null     int64
 10  profit       50 non-null     float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(6)
memory usage: 4.4+ KB

In [73]:
returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   return_order_id  8 non-null      object
 1   return_reason    8 non-null      object
dtypes: object(2)
memory usage: 256.0+ bytes

## Alias => rename

In [108]:
# SELECT sales AS total_sales => rename
orders_2 = orders.rename(
    columns = {
        'order_id' : 'id',
        'customer_id' : 'cust_id',
        'sales' : 'sale',
        'product_id' : 'prod_id'
    }

)

In [161]:
orders_2.head(1)

,id,order_date,ship_date,ship_mode,cust_id,region,prod_id,category,sale,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9

# Where

In [110]:
# SELECT * FROM Orders WHERE region='West';
orders.loc[
        orders.region == 'West', 
        ['order_id', 'customer_id', 'category']
].head(2)

         order_id customer_id         category
2  CA-2020-138688    DV-13045  Office Supplies
5  CA-2018-115812    BH-11710        Furniture

In [162]:
# SELECT customer_id, sales, profit FROM orders WHERE category='Furniture';
orders.loc[
        orders.category == 'Furniture',
        ['customer_id', 'sales', 'profit']
].head(4)

  customer_id  sales  profit
0    CG-12520  262.0    41.9
1    CG-12520  731.0   219.6
3    SO-20335  957.0  -383.0
5    BH-11710   48.0    14.2

### 1. AND and OR

In [112]:
# SELECT * FROM Orders WHERE region='West' AND sales > 500; 
# AND => &
orders.loc[
        (orders.region == 'West' ) & (orders.sales >= 1000)
]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3

In [113]:
# SELECT order_id	order_date	ship_date	ship_mode WHERE region='West' OR region='East'; |

orders.loc[
        (orders.region == 'West') | (orders.region == 'East'),
        ['order_id', 'order_date', 'ship_date', 'ship_mode', 'region']
    ].head(2)

         order_id  order_date   ship_date       ship_mode region
2  CA-2020-138688  12-06-2020  16-06-2020    Second Class   West
5  CA-2018-115812  09-06-2018  14-06-2018  Standard Class   West

## 2. NOT

In [163]:
#WHERE region != 'West'

orders.loc[
     (orders.region != 'South')
].head(4)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,case_statement
2,CA-2020-138688,2020-12-06,2020-06-16,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.0,2,6.9,Low
5,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.0,7,14.2,Low
6,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.0,4,2.0,Low
7,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.0,6,90.7,Medium

### 3. IN isin() & NOT IN ~

In [164]:
# SELECT * FROM orders WHERE region IN ('East','West','South');
orders.loc [
        ~(orders.region.isin(  ['East','West','South']  ))
].head(4)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,case_statement
14,US-2019-118983,2019-11-22,2019-11-26,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.0,5,-123.9,Low
15,US-2019-118983,2019-11-22,2019-11-26,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.0,3,-3.8,Low
16,CA-2018-105893,2018-11-11,2018-11-18,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.0,6,13.3,Medium
21,CA-2020-137330,2020-09-12,2020-12-13,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.0,7,5.1,Low

In [166]:
# SELECT * FROM orders WHERE region NOT IN ('East','West');
orders.loc[
        ~(orders.region.isin(['East', 'West']))
].head(4)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,case_statement
0,CA-2020-152156,2020-08-11,2020-11-11,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,Low
1,CA-2020-152156,2020-08-11,2020-11-11,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.0,3,219.6,Medium
3,US-2019-108966,2019-11-10,2019-10-18,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.0,5,-383.0,Medium
4,US-2019-108966,2019-11-10,2019-10-18,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.0,2,2.5,Low

### 4. Between

In [ ]:
# SELECT * FROM orders WHERE sales BETWEEN 1000 AND 3000;

In [37]:
orders.loc[
        orders.sales.between(1000, 3000)
]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5

### 5. Like  => .str.contains()

In [117]:
# SELECT * FROM orders WHERE category LIKE 'Fur%';
orders.loc[
        orders.category.str.contains('niture')
]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1

In [115]:
# SELECT * FROM orders WHERE category LIKE 'F%'; .str.startwith()
orders.loc[ orders.category.str.startswith('Fu')]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1

In [ ]:
# SELECT * FROM orders WHERE category LIKE '%ure'; .str.endswith()

### 6. filter dates

In [132]:
# SELECT * FROM orders WHERE order_date >= '2024-01-01';
orders.loc[
        orders.order_date >= '2024-01-01'
    ]

Empty DataFrame
Columns: [order_id, order_date, ship_date, ship_mode, customer_id, region, product_id, category, sales, quantity, profit]
Index: []

In [ ]:
# SELECT * FROM orders WHERE order_date BETWEEN '2024-01-01' AND '2024-03-31';

In [135]:
orders.loc[
        orders.order_date.between('2018-01-01', '2019-03-31')
    ]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
5,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.0,7,14.2
6,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.0,4,2.0
7,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.0,6,90.7
8,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.0,3,5.8
9,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.0,5,34.5
10,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.0,9,85.3
11,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.0,4,68.4
16,CA-2018-105893,2018-11-11,2018-11-18,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.0,6,13.3
17,CA-2018-167164,2018-05-13,2018-05-15,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.0,2,10.0
18,CA-2018-143336,2018-08-27,2018-01-09,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.0,2,2.5
19,CA-2018-143336,2018-08-27,2018-01-09,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.0,3,16.0
20,CA-2018-143336,2018-08-27,2018-01-09,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.0,4,7.4
46,CA-2018-146703,2018-10-20,2018-10-25,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5

In [137]:
orders.loc[
        orders.order_date.dt.year == 2018
    ]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
5,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.0,7,14.2
6,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.0,4,2.0
7,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.0,6,90.7
8,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.0,3,5.8
9,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.0,5,34.5
10,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.0,9,85.3
11,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.0,4,68.4
16,CA-2018-105893,2018-11-11,2018-11-18,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.0,6,13.3
17,CA-2018-167164,2018-05-13,2018-05-15,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.0,2,10.0
18,CA-2018-143336,2018-08-27,2018-01-09,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.0,2,2.5
19,CA-2018-143336,2018-08-27,2018-01-09,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.0,3,16.0
20,CA-2018-143336,2018-08-27,2018-01-09,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.0,4,7.4
46,CA-2018-146703,2018-10-20,2018-10-25,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5

## Order By

In [167]:
#SELECT * FROM Orders ORDER BY sales DESC peofit ASC;
orders.sort_values(
       by = ['sales', 'profit'],
        ascending = [False, True]
).head(5)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,case_statement
27,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.0,7,-1665.1,High
10,CA-2018-115812,2018-09-06,2018-06-14,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.0,9,85.3,High
35,CA-2020-117590,2020-08-12,2020-10-12,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.0,7,123.5,High
24,CA-2019-106320,2019-09-25,2019-09-30,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.0,3,240.3,High
3,US-2019-108966,2019-11-10,2019-10-18,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.0,5,-383.0,Medium

## Creating New Columns

In [168]:
# SELECT *,sales*0.18 AS gst FROM Orders;
# using lambda functions 
orders['sales_gst'] = orders.sales * 0.18
orders.head(5)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,case_statement,sales_gst
0,CA-2020-152156,2020-08-11,2020-11-11,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,Low,47.16
1,CA-2020-152156,2020-08-11,2020-11-11,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.0,3,219.6,Medium,131.58
2,CA-2020-138688,2020-12-06,2020-06-16,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.0,2,6.9,Low,2.52
3,US-2019-108966,2019-11-10,2019-10-18,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.0,5,-383.0,Medium,172.26
4,US-2019-108966,2019-11-10,2019-10-18,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.0,2,2.5,Low,3.96

In [169]:
#SELECT *,sales-profit AS cost FROM Orders;
orders['cost'] = orders.sales - orders.profit

orders.head(1)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,case_statement,sales_gst,cost
0,CA-2020-152156,2020-08-11,2020-11-11,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,Low,47.16,220.1

In [54]:
#SELECT * (profit/sales)*100 AS margin FROM Orders;
orders['margin'] = (orders.profit / orders.sales) * 100

orders.head(5)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,sales_gst,cost,margin
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,47.160,220.1,15.992366
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,131.742,512.3,30.004099
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,2.628,7.7,47.260274
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,172.368,1340.6,-39.995823
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,4.032,19.9,11.160714

## Filtering NULL

In [40]:
# WHERE profit IS NULL
orders.loc[orders['profit'].isna()]

Empty DataFrame
Columns: [order_id, order_date, ship_date, ship_mode, customer_id, region, product_id, category, sales, quantity, profit]
Index: []

In [170]:
# # WHERE profit IS NOT NULL
orders.loc[orders['profit'].notna()].head(5)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,case_statement,sales_gst,cost
0,CA-2020-152156,2020-08-11,2020-11-11,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,Low,47.16,220.1
1,CA-2020-152156,2020-08-11,2020-11-11,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.0,3,219.6,Medium,131.58,511.4
2,CA-2020-138688,2020-12-06,2020-06-16,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.0,2,6.9,Low,2.52,7.1
3,US-2019-108966,2019-11-10,2019-10-18,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.0,5,-383.0,Medium,172.26,1340.0
4,US-2019-108966,2019-11-10,2019-10-18,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.0,2,2.5,Low,3.96,19.5

## Distinct

In [46]:
#unique()
orders.region.unique()
# COUNT(DISTINCT customer_id) => nunique()
orders.region.nunique()

4

## Drop Duplicates

In [171]:
# drop duplicates => drop_duplicates()

orders.drop_duplicates().head(5)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,case_statement,sales_gst,cost
0,CA-2020-152156,2020-08-11,2020-11-11,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,Low,47.16,220.1
1,CA-2020-152156,2020-08-11,2020-11-11,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.0,3,219.6,Medium,131.58,511.4
2,CA-2020-138688,2020-12-06,2020-06-16,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.0,2,6.9,Low,2.52,7.1
3,US-2019-108966,2019-11-10,2019-10-18,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.0,5,-383.0,Medium,172.26,1340.0
4,US-2019-108966,2019-11-10,2019-10-18,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.0,2,2.5,Low,3.96,19.5

## GroupBy

In [140]:
#SELECT region, SUM(sales) AS total_sales FROM Orders GROUP BY region;

orders.groupby('region').sales.sum()

region
Central    3818.0
East       3463.0
South      2082.0
West       5653.0
Name: sales, dtype: float64

In [142]:
# SELECT region, SUM(sales), AVG(profit), COUNT(*) FROM Orders GROUP BY region;
(
    orders
    .groupby('region')
    .agg(
        total_sales = ('sales', 'sum'),
        avg_profit = ('profit', 'mean'),
        no_of_counts = ('order_id', 'count')
    )
)

         total_sales  avg_profit  no_of_counts
region
Central       3818.0   -1.294118            17
East          3463.0 -163.800000            10
South         2082.0  -17.333333             6
West          5653.0   43.323529            17

In [144]:
# SELECT region,AVG(profit)FROM Orders GROUP BY region;

orders.groupby('region').profit.mean()

region
Central     -1.294118
East      -163.800000
South      -17.333333
West        43.323529
Name: profit, dtype: float64

In [62]:
# SELECT category, AVG(profit), MAX(sales), MIN(sales) FROM Orders GROUP BY category;

orders.groupby('category').agg(
    avg_profit = ('profit', 'mean'),
    max_sales = ('sales', 'max'),
    min_sales =  ('sales', 'min')
)

                 avg_profit  max_sales  min_sales
category
Furniture       -136.866667     3083.4       48.9
Office Supplies    7.685714      665.9        2.5
Technology        39.970000     1097.5       21.8

## Case Statment using numpy

In [69]:
# condition
_conditions = [
    orders.profit > 100,
    (orders.profit < 100) | (orders.profit > 0),
    orders.profit < 0
]
# choices
_choices = ['high-profit', 'moderate-profit', 'loss']

# apply logic
orders['case_statement_2'] = np.select( _conditions, _choices, default = 'unknown')

print(orders.tail(5))

          order_id  order_date   ship_date       ship_mode customer_id  \
45  CA-2020-118255  11-03-2020  13-03-2020     First Class    ON-18715
46  CA-2018-146703  20-10-2018  25-10-2018    Second Class    PO-18865
47  CA-2020-169194  20-06-2020  25-06-2020  Standard Class    LH-16900
48  CA-2020-169194  20-06-2020  25-06-2020  Standard Class    LH-16900
49  CA-2019-115742  18-04-2019  22-04-2019  Standard Class    DP-13000

     region       product_id         category  sales  quantity  profit  \
45  Central  OFF-BI-10003291  Office Supplies   17.5         2     8.2
46  Central  OFF-ST-10001713  Office Supplies  212.0         4     8.5
47     East  TEC-AC-10002167       Technology   45.0         3     5.0
48     East  TEC-PH-10003988       Technology   21.8         2     6.1
49  Central  OFF-BI-10004410  Office Supplies   38.2         6    18.0

    sales_gst   cost     margin   case_statement case_statement_2
45      3.150    9.3  46.857143  moderate-profit  moderate-profit
46     38.160  203.5   4.009434  moderate-profit  moderate-profit
47      8.100   40.0  11.111111  moderate-profit  moderate-profit
48      3.924   15.7  27.981651  moderate-profit  moderate-profit
49      6.876   20.2  47.120419  moderate-profit  moderate-profit

In [66]:
orders.head(5)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,sales_gst,cost,margin,case_statement
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,47.160,220.1,15.992366,moderate-profit
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,131.742,512.3,30.004099,High-profit
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,2.628,7.7,47.260274,moderate-profit
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,172.368,1340.6,-39.995823,moderate-profit
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,4.032,19.9,11.160714,moderate-profit

In [73]:
# Count Missing Values orders.isna().sum()
orders.isna().sum()

order_id            0
order_date          0
ship_date           0
ship_mode           0
customer_id         0
region              0
product_id          0
category            0
sales               0
quantity            0
profit              0
sales_gst           0
cost                0
margin              0
case_statement      0
case_statement_2    0
dtype: int64

## Fill Missing Values

In [37]:
# SELECT COALESCE(profit,0) FROM orders; => fillna()

In [154]:

df = pd.DataFrame({
    "region": ["East", "West", None, "South"],
    "sales": [500, None, 300, None]
})

df.fillna({
        'region' : 'unknow',
        'sales' : 0    
}, inplace = True)


df

   region  sales
0    East  500.0
1    West    0.0
2  unknow  300.0
3   South    0.0

In [38]:
# Fill Different Columns .fillna({:})

In [40]:
# Check If Any Missing Values Exist => orders.isna().any().any()

## Case Statement #using numpy

In [175]:
""" SELECT order_id,sales,
    CASE
        WHEN sales >= 1000 THEN 'High'
        WHEN sales >= 500 THEN 'Medium'
        ELSE 'Low'
    END AS sales_category
FROM orders; """

_condititions = [
    orders.sales >= 1000,
    orders.sales >= 500,
    orders.sales < 500
]

_choices = ['High', 'Medium', 'Low' ]

import numpy as pd
orders['case_statement'] = np.select(_condititions,_choices, default= 'unknown' )

In [176]:
orders.head(2)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,case_statement,sales_gst,cost
0,CA-2020-152156,2020-08-11,2020-11-11,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,Low,47.16,220.1
1,CA-2020-152156,2020-08-11,2020-11-11,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.0,3,219.6,Medium,131.58,511.4

# JOINS => merge

### 1. Inner Join

In [149]:
df1 = pd.DataFrame({
    "Name": ["John", "Alice", "Bob", "Eve"],
    "Age": [25, 30, 22, 35]
})

df2 = pd.DataFrame({
    "Name": ["John", "Alice", "Bob", "Charlie"],
    "Salary": [50000, 55000, 40000, 48000]
})

#select * from df1 inner join df2 ON df1.name = df2.name

df1.merge( df2, on= 'Name', how= 'inner' )

      Name   Age   Salary
0     John  25.0  50000.0
1    Alice  30.0  55000.0
2      Bob  22.0  40000.0
3      Eve  35.0      NaN
4  Charlie   NaN  48000.0

### 2. Left Join

In [152]:
df1.merge( df2, on= 'Name', how= 'left' )

    Name  Age   Salary
0   John   25  50000.0
1  Alice   30  55000.0
2    Bob   22  40000.0
3    Eve   35      NaN

### 3. right Join

In [151]:
df1.merge( df2, on= 'Name', how= 'right' )

      Name   Age  Salary
0     John  25.0   50000
1    Alice  30.0   55000
2      Bob  22.0   40000
3  Charlie   NaN   48000

### 4. Full Join

In [150]:
df1.merge( df2, on= 'Name', how= 'outer' )

      Name   Age   Salary
0     John  25.0  50000.0
1    Alice  30.0  55000.0
2      Bob  22.0  40000.0
3      Eve  35.0      NaN
4  Charlie   NaN  48000.0